In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import statsmodels.api as sm
import xlrd

%matplotlib inline
sns.set_palette("pastel")

## FTAs exploration of the chosen countrie's trading partners and knowing their diversification and types of FTAs

       Using excel file from the WTO.

In [48]:
# Excel sheet that shows FTAs and the provisions that fall under the 
# current mandate of the WTO
fta = pd.read_excel('pta-agreements_1.xls',
                    sheet_name='WTO+ AC')

In [16]:
pd.set_option('display.max_rows', None)

In [47]:
fta.head()

,Agreement,Date,year,Type,FTAIndustrial,FTAAgriculture,Customs,ExportTaxes,SPS,TBT,STE,AD,CVM,StateAid,PublicProcurement,TRIMs,GATS,TRIPs
0,ASEAN free trade area,28-Jan-92,1992,FTA,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,ASEAN-Australia-New Zealand,1-Jan-10,2010,FTA & EIA,1,1,1,1,1,1,0,1,1,0,0,1,1,1
2,ASEAN-India,1-Jan-10,2010,FTA & EIA,1,1,1,1,1,1,0,0,0,0,0,1,1,1
3,ASEAN-Korea,1-Jan-10,2010,FTA & EIA,1,1,1,0,1,1,1,1,1,1,0,1,1,1
4,Australia-New Zealand (ANZCERTA),1-Jan-83,1983,FTA & EIA,1,1,1,0,0,1,0,1,1,1,0,0,1,0

### Country specific FTA's

In [51]:
countries = ['Brazil', 'Mexico', 'Argentina', 'Chile', 'Indonesia', 'Japan', 'Korea', 'India']

In [78]:
fta[fta['Agreement'].str.contains('India')]

,Agreement,Date,year,Type,FTAIndustrial,FTAAgriculture,Customs,ExportTaxes,SPS,TBT,STE,AD,CVM,StateAid,PublicProcurement,TRIMs,GATS,TRIPs
2,ASEAN-India,1-Jan-10,2010,FTA & EIA,1,1,1,1,1,1,0,0,0,0,0,1,1,1
64,India-Japan,1-Aug-11,2011,FTA & EIA,1,1,1,1,1,1,0,1,1,1,1,1,1,1
65,India-Malaysia,1-Jul-11,2011,FTA & EIA,1,1,1,0,1,1,0,1,0,0,0,0,1,0
66,India-Singapore,1-Aug-05,2005,FTA & EIA,1,1,1,0,1,1,1,1,1,1,0,1,1,0
67,India-Sri Lanka,15-Dec-01,2001,FTA,1,1,1,0,0,0,1,1,0,0,0,0,0,0
77,"Korea, Republic of-India",1-Jan-10,2010,FTA & EIA,1,1,1,1,1,1,1,1,1,1,1,1,1,1
80,MERCOSUR-India,1-Jun-09,2009,PSA,1,1,0,0,1,1,1,1,1,0,0,0,0,0
156,Chile - India,17-Aug-07,2007,PSA,1,1,1,0,1,1,1,1,1,1,0,0,0,0
225,India - Afghanistan,13-May-03,2003,PSA,1,1,1,0,0,0,1,0,0,0,0,0,0,0
226,India - Bhutan,29-Jul-06,2006,FTA,1,1,0,0,0,0,0,0,0,0,0,0,0,0
227,India - Nepal,27-Oct-09,2009,PSA,1,1,1,1,1,0,0,0,0,0,0,0,0,0

In [65]:
for ftas in countries:
    print('---------------------')
    print(ftas)
    print(fta['Agreement'].str.contains(ftas).value_counts())

---------------------
Brazil
False    279
Name: Agreement, dtype: int64
---------------------
Mexico
False    270
True       9
Name: Agreement, dtype: int64
---------------------
Argentina
False    279
Name: Agreement, dtype: int64
---------------------
Chile
False    257
True      22
Name: Agreement, dtype: int64
---------------------
Indonesia
False    278
True       1
Name: Agreement, dtype: int64
---------------------
Japan
False    265
True      14
Name: Agreement, dtype: int64
---------------------
Korea
False    268
True      11
Name: Agreement, dtype: int64
---------------------
India
False    268
True      11
Name: Agreement, dtype: int64

        Brazil and Argentina do not show any FTAs because they are involved in Trade blocs. The other countries are also involved in trade blocs, so for the values shown as True are incomplete.

### Trade blocs

In [73]:
fta[fta['Agreement'].str.contains('ASEAN')]

,Agreement,Date,year,Type,FTAIndustrial,FTAAgriculture,Customs,ExportTaxes,SPS,TBT,STE,AD,CVM,StateAid,PublicProcurement,TRIMs,GATS,TRIPs
0,ASEAN free trade area,28-Jan-92,1992,FTA,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,ASEAN-Australia-New Zealand,1-Jan-10,2010,FTA & EIA,1,1,1,1,1,1,0,1,1,0,0,1,1,1
2,ASEAN-India,1-Jan-10,2010,FTA & EIA,1,1,1,1,1,1,0,0,0,0,0,1,1,1
3,ASEAN-Korea,1-Jan-10,2010,FTA & EIA,1,1,1,0,1,1,1,1,1,1,0,1,1,1
19,China-ASEAN,1-Jan-05,2005,FTA & EIA,1,1,0,0,0,0,0,1,1,0,0,1,1,0
68,Japan-ASEAN,1-Dec-08,2008,FTA,1,1,1,0,1,1,0,1,1,0,0,1,1,0

|Country |  PTAs | Trade Blocs |
|--- | --- | --- |
| Brazil | 0 | 0 |
| Mexico | 0 | 0 |
| Argentina | 0 | 0 |
| Chile | 0 | 0 |
| Indonesia | 0 | 1 |
| Japan | 0 | 0 |
| South Korea | 0 | 0 |
| India | 0 | 0 |

ASEAN: Indonesia

In [35]:
Chile_ftas = fta[fta['Agreement'].str.contains('Chile')].reset_index()

In [36]:
Chile_ftas['Agreement']

0                                   Chile-Australia
1                                       Chile-China
2                                       Chile-Japan
3                                       Chile-Korea
4                                          EC-Chile
5                                          US-Chile
6                                    Canada - Chile
7                                  Chile - Malaysia
8                                      Peru - Chile
9                                  Chile - Colombia
10     Chile - Costa Rica (Chile - Central America)
11    Chile - El Salvador (Chile - Central America)
12      Chile - Guatemala (Chile - Central America)
13       Chile - Honduras (Chile - Central America)
14      Chile - Nicaragua (Chile - Central America)
15                                     EFTA - Chile
16                         Hong Kong, China - Chile
17                                   Panama - Chile
18                                   Chile - Mexico
19                                 Chile - Viet nam
20                                   Turkey - Chile
21                                   Chile - India
Name: Agreement, dtype: object

In [37]:
Chile_ftas.shape

(22, 19)

In [29]:
fta_extra = pd.read_excel('pta-agreements_1.xls',
                    sheet_name='WTO-X AC')

In [71]:
fta_extra['Agreement']

0                                  ASEAN free trade area
1                            ASEAN-Australia-New Zealand
2                                            ASEAN-India
3                                            ASEAN-Korea
4                       Australia-New Zealand (ANZCERTA)
5                                    Australia-Singapore
6                                     Australia-Thailand
7                                               CAFTA-DR
8                                                    CAN
9                                                  CEFTA
10                                                   CEZ
11                                                   CIS
12                                                COMESA
13                                           Canada-EFTA
14                                           Canada-Peru
15                                       Chile-Australia
16                                           Chile-China
17                                           Chile-Japan
18                                           Chile-Korea
19                                           China-ASEAN
20                                       China-Hong Kong
21                                     China-New Zealand
22                                        China-Pakistan
23                                            China-Peru
24                                       China-Singapore
25                                                  EAEC
26                                   EC Enlargement (12)
27                                   EC Enlargement (15)
28                                   EC Enlargement (25)
29                                   EC Enlargement (27)
30                                             EC Treaty
31                                            EC-Albania
32                                            EC-Algeria
33                                 EC-Bosnia Herzegovina
34                                          EC-CARIFORUM
35                                           EC-Cameroon
36                                              EC-Chile
37                                            EC-Croatia
38                                      EC-Côte d'Ivoire
39                                              EC-Egypt
40                                      EC-FYR Macedonia
41                                      EC-Faroe Islands
42                                            EC-Iceland
43                                             EC-Israel
44                                             EC-Jordan
45                                            EC-Lebanon
46                                             EC-Mexico
47                                         EC-Montenegro
48                                            EC-Morocco
49                                             EC-Norway
50                               EC-Overseas Territories
51                              EC-Palestinian Authority
52                                       EC-South Africa
53                            EC-Switzerland Liechtenst0
54                                              EC-Syria
55                                            EC-Tunisia
56                                             EC-Turkey
57                                                ECOWAS
58                                                   EEA
59                                           EFTA-Israel
60                                            EFTA-Korea
61                                         EU-San Marino
62                                             EU-Serbia
63                                                   GCC
64                                           India-Japan
65                                        India-Malaysia
66                                       India-Singapore
67                                       India-Sri Lanka
68                                           Japan-ASEAN
69                                       Japan-Indonesia
70                                        Japan-Malaysia
71                                          Japan-Mexico
72                                     Japan-Philippines
73                                       Japan-Singapore
74                                     Japan-Switzerland
75                                        Japan-Thailand
76                                        Japan-Viet Nam
77                              Korea, Republic of-India
78                          Korea, Republic of-Singapore
79                                              MERCOSUR
80                                        MERCOSUR-India
81                                                 NAFTA
82                                                 PAFTA
83                            Russian Federation-Ukraina
84                                                  SACU
85                                                 SAFTA
86                Southern African Development Community
87                                           Turkey-EFTA
88                                          US-Australia
89                                            US-Bahrain
90                                              US-Chile
91                                             US-Israel
92                                             US-Jordan
93                                            US-Morocco
94                                               US-Oman
95                                               US-Peru
96                                          US-Singapore
97                                       Ukraine-Belarus
98                                    Ukraine-Kazakhstan
99                                  Ukraine-Turkmenistan
100                                    Japan - Australia
101                                 Malaysia - Australia
102                Australia - Papua New Guinea (PATCRA)
103                       Korea, Republic of - Australia
104                            Brunei Darussalam - Japan
105         Trans-Pacific Strategic Economic Partnership
106                                       Canada - Chile
107                                    Canada - Colombia
108                                  Canada - Costa Rica
109                                    Canada - Honduras
110                                      Canada - Israel
111                                      Canada - Jordan
112                                      Canada - Panama
113                               Canada - Rep. of Korea
114                                     Chile - Malaysia
115                                         Peru - Chile
116                                     Chile - Colombia
117         Chile - Costa Rica (Chile - Central America)
118        Chile - El Salvador (Chile - Central America)
119          Chile - Guatemala (Chile - Central America)
120           Chile - Honduras (Chile - Central America)
121          Chile - Nicaragua (Chile - Central America)
122                                         EFTA - Chile
123                             Hong Kong, China - Chile
124                                       Panama - Chile
125                                       Chile - Mexico
126                                     Chile - Viet nam
127                                       Turkey - Chile
128                                         Japan - Peru
129                               New Zealand - Malaysia
130                                  Pakistan - Malaysia
131                                    Colombia - Mexico
132                                        Peru - Mexico
133                                        EFTA - Mexico
134                                      Israel - Mexico
135                             Mexico - Central America
136                                     Mexico - Uruguay
137                              New Zealand - Singapore
138                       Hong Kong, China - New Zealand
139                         New Zealand - Chinese Taipei
140                               Thailand - New Zealand
141                                     Peru - Singapore
142                                    Costa Rica - Peru
143                                          EFTA - Peru
144                               EU - Colombia and Peru
145                                        Panama - Peru
146                            Peru - Korea, Republic of
147                               Costa Rica - Singapore
148                                     EFTA - Singapore
149           Gulf Cooperation Council (GCC) - Singapore
150                                   Jordan - Singapore
151                                   Panama - Singapore
152                           Singapore - Chinese Taipei
153                              Korea, Republic of - US
154                                        US - Colombia
155                                          US - Panama
156                                       Chile - India
157    Global System of Trade Preferences among devel...
158        Latin American Integration Association (LAIA)
159                 Protocol on Trade Negotiations (PTN)
160    South Pacific Regional Trade and Economic Coop...
161                                Armenia - Kazakhstan
162                                   Armenia - Moldova
163                         Armenia - Russian Federation
164                               Armenia - Turkmenistan
165                                    Armenia - Ukraine
166                  Asia Pacific Trade Agreement (APTA)
167    Asia Pacific Trade Agreement (APTA) - Accessio...
168    Carribean Community and Community Market (CARI...
169                Central American Common Market (CACM)
170                                   China - Costa Rica
171                                 China - Macao, China
172    Colombia - Northern Triangle (El Salvador, Gua...
173                 Dominican Republic - Central America
174                         East African Community (EAC)
175    East African Community (EAC) - Accession of Bu...
176    East African Community (EAC) - Accession of Rw...
177                                  EC (10) Enlargement
178                                   EC (9) Enlargement
179    Economic and Monetary Community of Central Afr...
180              Economic Cooperation Organization (ECO)
181                          EFTA - Accession of Iceland
182                                       EFTA - Albania
183                        EFTA - Bosnia and Herzegovina
184       EFTA - Central America (Costa Rica and Panama)
185                                      EFTA - Colombia
186                                         EFTA - Egypt
187         EFTA - Former Yugoslav Republic of Macedonia
188                              EFTA - Hong Kong, China
189                                        EFTA - Jordan
190                                       EFTA - Lebanon
191                                    EFTA - Montenegro
192                                       EFTA - Morocco
193                         EFTA - Palestinian Authority
194                                          EFTA - SACU
195                                        EFTA - Serbia
196                                       EFTA - Tunisia
197                                       EFTA - Ukraine
198                                       Egypt - Turkey
199                                   El Salvador - Cuba
200              El Salvador - Honduras - Chinese Taipei
201                                         EU - Andorra
202                                 EU - Central America
203    EU - Eastern and Southern Africa States Interi...
204                                         EU - Georgia
205                              EU - Korea, Republic of
206                           EU - Papua New Guinea/Fiji
207                             EU - Republic of Moldova
208                                         EU - Ukraine
209                                  EU (28) Enlargement
210                       Eurasian Economic Union (EAEU)
211    Eurasian Economic Union (EAEU) - Accession of ...
212    Eurasian Economic Union (EAEU) - Accession of ...
213               European Free Trade Association (EFTA)
214                               Faroe Islands - Norway
215                          Faroe Islands - Switzerland
216                                    Georgia - Armenia
217                                 Georgia - Azerbaijan
218                                 Georgia - Kazakhstan
219                         Georgia - Russian Federation
220                               Georgia - Turkmenistan
221                                    Georgia - Ukraine
222                           Guatemala - Chinese Taipei
223                                      Iceland - China
224                              Iceland - Faroe Islands
225                                  India - Afghanistan
226                                       India - Bhutan
227                                        India - Nepal
228                          Korea, Republic of - Turkey
229                            Kyrgyz Republic - Armenia
230                         Kyrgyz Republic - Kazakhstan
231                            Kyrgyz Republic - Moldova
232                 Kyrgyz Republic - Russian Federation
233                            Kyrgyz Republic - Ukraine
234                         Kyrgyz Republic - Uzbekistan
235          Lao People's Democratic Republic - Thailand
236                                 Mauritius - Pakistan
237                     Melanisian Spearhead Group (MSG)
238                           Nicaragua - Chinese Taipei
239     Pacific Island Countries Trade Agreement (PICTA)
240                                 Pakistan - Sri Lanka
241                              Panama - Chinese Taipei
242       Panama - Costa Rica (Panama - Central America)
243      Panama - El Salvador (Panama - Central America)
244         Panama - Guatemala (Panama - Central America
245         Panama - Honduras (Panama - Central America)
246        Panama - Nicaragua (Panama - Central America)
247                      Russian Federation - Azerbaijan
248                         Russian Federation - Belarus
249            Russian Federation - Belarus - Kazakhstan
250                      Russian Federation - Kazakhstan
251             Russian Federation - Republic of Moldova
252                          Russian Federation - Serbia
253                      Russian Federation - Tajikistan
254                    Russian Federation - Turkmenistan
255                     Russian Federation - Uzkbekistan
256     South Asian Preferential Trade Agreement (SAPTA)
257                                  Switzerland - China
258    Treaty on a Free Trade Area between members of...
259                                     Turkey - Albania
260                      Turkey - Bosnia and Herzegovina
261       Turkey - Former Yugoslav Republic of Macedonia
262                                     Turkey - Georgia
263                                      Turkey - Israel
264                                      Turkey - Jordan
265                                   Turkey - Mauritius
266                                  Turkey - Montenegro
267                                     Turkey - Morocco
268                       Turkey - Palestinian Authority
269                                      Turkey - Serbia
270                                       Turkey - Syria
271                                     Turkey - Tunisia
272                                 Ukraine - Azerbaijan
273      Ukraine - Former Yugoslav Republic of Macedonia
274                                    Ukraine - Moldova
275                                 Ukraine - Montenegro
276                                   Ukraine Tajikistan
277                                 Ukraine - Uzbekistan
278     West African Economic and Monetary Union (WAEMU)
Name: Agreement, dtype: object

In [31]:
fta_extra.head()

,Agreement,Date,year,Type,AntiCorruption,CompetitionPolicy,EnvironmentalLaws,IPR,Investment,LabourMarketRegulation,...,PoliticalDialogue,PublicAdministration,RegionalCooperation,ResearchandTechnology,SME,SocialMatters,Statistics,Taxation,Terrorism,VisaandAsylum
0,ASEAN free trade area,28-Jan-92,1992,FTA,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ASEAN-Australia-New Zealand,1-Jan-10,2010,FTA & EIA,0,1,0,1,1,0,...,0,0,1,0,0,0,0,0,0,1
2,ASEAN-India,1-Jan-10,2010,FTA & EIA,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ASEAN-Korea,1-Jan-10,2010,FTA & EIA,0,0,1,1,1,0,...,0,0,0,1,1,0,0,0,0,0
4,Australia-New Zealand (ANZCERTA),1-Jan-83,1983,FTA & EIA,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [33]:
Chile_f_extra = fta_extra[fta_extra['Agreement'].str.contains('Chile')].reset_index()

In [72]:
Chile_f_extra.head()

,index,Agreement,Date,year,Type,AntiCorruption,CompetitionPolicy,EnvironmentalLaws,IPR,Investment,...,PoliticalDialogue,PublicAdministration,RegionalCooperation,ResearchandTechnology,SME,SocialMatters,Statistics,Taxation,Terrorism,VisaandAsylum
0,15,Chile-Australia,6-Mar-09,2009,FTA & EIA,0,1,1,0,1,...,0,0,1,1,0,0,0,0,0,0
1,16,Chile-China,1-Oct-06,2006,FTA & EIA,0,0,1,1,1,...,0,1,0,1,1,1,0,1,1,1
2,17,Chile-Japan,3-Sep-07,2007,FTA & EIA,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,18,Chile-Korea,1-Apr-04,2004,FTA & EIA,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,1
4,36,EC-Chile,1-Feb-03,2003,FTA & EIA,0,1,1,1,1,...,1,1,1,1,1,1,1,0,1,0

|Country | PTAs | Trade Blocs |
|--- | --- | --- |
| Brazil | 0 |